### ISSUE TITLE
ERR: docker image grafana4iot not available

### ISSUE THREAD

**Issue by josselArth** [ibm-watson-iot/grafana4iot#1]
Hello,
I would like to use the Grafana4iot repository for IBW iot Platform.
But when I lunch the command line "docker-compose up", I have this error:

ERROR: {
    "code": "IC5051E",
    "description": "The image grafana4iot could not be retrieved. Verify that the image ID or name is correct.",
    "incident_id": "3694-1473255037.163-21701187",
    "name": "ImageNotFound",
    "rc": "404",
    "type": "Infrastructure"
}

**Comment by durera** [comment]
Did you follow the steps from the README, if not, what steps exactly were you performing?

```
[root@localhost ~]# export IOT_API_KEY=<your api key>
[root@localhost ~]# export IOT_API_TOKEN=<your auth token>
[root@localhost ~]# git clone https://github.com/ibm-watson-iot/connector-statsd
[root@localhost ~]# git clone https://github.com/ibm-watson-iot/grafana4iot
[root@localhost ~]# cd grafana4iot
[root@localhost ~]# docker-compose up
```

I just ran these commands on my test system and everything came up?

**Comment by durera** [comment]
I've updated the docker-compose file to support build from github under https://github.com/ibm-watson-iot/grafana4iot/commit/4974ee72076225935e2f78f4e3b91532e771f012, so try the following:

```
[root@localhost ~]# export IOT_API_KEY=<your api key>
[root@localhost ~]# export IOT_API_TOKEN=<your auth token>
[root@localhost ~]# wget https://github.com/ibm-watson-iot/grafana4iot/blob/master/docker-compose.yml
[root@localhost ~]# docker-compose up
```
